version: "3.8"

services:
  todolist-app:
    build: .
    container_name: todolist-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: "3306"
      DB_DATABASE: todolist_db
      DB_USERNAME: root
      DB_PASSWORD: ""

networks:
  laravel:
    driver: bridge